apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.sync.tokenSecretName }}
  namespace: {{ include "simple-volume.namespace" . }}
type: Opaque
stringData:
  {{ .Values.sync.tokenSecretKey }}: {{ .Values.sync.token | quote }}

