{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "simple-volume.serviceAccountName" . }}
  namespace: {{ include "simple-volume.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "simple-volume.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

